export const bannerSliderData = [
    {
      id: 1,
      title: "Stylish Mens Jackets",
      description: "Upgrade your wardrobe with our latest collection of men's jackets. Perfect for any season.",
      buttonText: "Shop Now",
      image: "https://images.pexels.com/photos/10274665/pexels-photo-10274665.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",  
      yAxisPosition:"center",
      xAxisPosition:"start",
      textPosition:"start",
      maxWidth:"50%"
    },
    {
      id: 2,
      title: "Trending T-Shirts for Men",
      description: "Find the perfect t-shirt that complements your style. Available in various designs and colors.",
      buttonText: "Explore Now",
      image: "https://images.pexels.com/photos/9558251/pexels-photo-9558251.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",  
      yAxisPosition:"end",
      xAxisPosition:"start",
      textPosition:"start",
      maxWidth:"50%"
    },
    {
      id: 3,
      title: "Wireless Headphones",
      description: "Experience high-quality sound with our latest wireless headphones. Comfort and performance combined.",
      buttonText: "Shop Now",
      image: "https://images.pexels.com/photos/8038326/pexels-photo-8038326.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2", 
      yAxisPosition:"end",
      xAxisPosition:"end",
      textPosition:"start",
      maxWidth:"50%" 
    },
    {
      id: 4,
      title: "Smartphone Deals",
      description: "Check out the best deals on top smartphones. Fast shipping and great prices on all models.",
      buttonText: "Shop Now",
      image: "https://waltonbd.com/image/catalog/category-banner/mobile/nexg-n8-new.jpg",  
      yAxisPosition:"start",
      xAxisPosition:"end",
      textPosition:"start",
      maxWidth:"50%"
    },
    {
      id: 5,
      title: "Men's Casual Shoes",
      description: "Step into comfort with our range of men's casual shoes. Stylish designs for every occasion.",
      buttonText: "Shop Now",
      image: "https://images.pexels.com/photos/1598505/pexels-photo-1598505.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
      yAxisPosition:"center",
      xAxisPosition:"center",
      textPosition:"center",
      maxWidth:"50%"  
    },
  ]



  export const featuredProducts = [
    {
      id: 1,
      name: "Wireless Bluetooth Headphones",
      description: "High-quality sound with noise cancellation. Long-lasting battery life, perfect for travel and sports.",
      price: 129.99,
      discount: 20, // Percentage discount
      image: "https://www.startech.com.bd/image/cache/catalog/headphone/havit/h2590bt-pro/h2590bt-pro-01-500x500.webp",
      category: "Electronics",
      rating: 3.5,
      stock: 25,
      brand: "SoundPro",
      tags: ["wireless", "bluetooth", "headphones"],
      isNew: false,
      isFeatured: true,
    },
    {
      id: 2,
      name: "Smartphone 256GB Storage",
      description: "Latest model with a 6.5-inch OLED display, 256GB storage, and high-resolution camera.",
      price: 799.99,
      discount: 15,
      image: "https://www.startech.com.bd/image/cache/catalog/mobile/samsung/galaxy-z-flip4/galaxy-z-flip4-001-500x500.webp",
      category: "Electronics",
      rating: 4.7,
      stock: 40,
      brand: "TechMaster",
      tags: ["smartphone", "android", "5G"],
      isNew: true,
      isFeatured: true,
    },
    {
      id: 3,
      name: "Ergonomic Office Chair",
      description: "Adjustable chair with lumbar support and comfortable cushioning for long hours of sitting.",
      price: 199.99,
      discount: 10,
      image: "https://img.drz.lazcdn.com/static/bd/p/1232a69525893adc8dc663774bcb9c5e.jpg_720x720q80.jpg_.webp",
      category: "Furniture",
      rating: 4.3,
      stock: 15,
      brand: "ComfyLiving",
      tags: ["office", "furniture", "ergonomic"],
      isNew: false,
      isFeatured: true,
    },
    {
      id: 4,
      name: "Laptop Backpack with USB Charging Port",
      description: "Stylish and durable backpack with a built-in USB charging port, ideal for students and professionals.",
      price: 49.99,
      discount: 5,
      image: "/images/laptop-backpack.jpg",
      category: "Accessories",
      rating: 4.6,
      stock: 50,
      brand: "UrbanGear",
      tags: ["backpack", "laptop", "accessories"],
      isNew: true,
      isFeatured: false,
    },
    {
      id: 5,
      name: "Electric Toothbrush with 4 Modes",
      description: "Advanced electric toothbrush with three cleaning modes and long battery life for a healthier smile.",
      price: 89.99,
      discount: 25,
      image: "	https://img.drz.lazcdn.com/static/bd/p/aa97cea924c583c9c2aa71139062d95d.jpg_720x720q80.jpg_.webp",
      category: "Health & Beauty",
      rating: 4.8,
      stock: 60,
      brand: "SmileTech",
      tags: ["electric", "toothbrush", "health"],
      isNew: false,
      isFeatured: true,
    },
    {
      id: 6,
      name: "Leather Wallet",
      description: "Premium leather wallet with multiple card slots and a sleek design, perfect for everyday use.",
      price: 39.99,
      discount: 10,
      image: "/images/leather-wallet.jpg",
      category: "Accessories",
      rating: 4.4,
      stock: 100,
      brand: "LeatherCraft",
      tags: ["wallet", "leather", "accessories","water bottle"],
      isNew: false,
      isFeatured: false,
    },
    {
      id: 7,
      name: "Stainless Steel Water Bottle",
      description: "Eco-friendly water bottle with double-wall insulation to keep your drinks hot or cold for hours.",
      price: 29.99,
      discount: 15,
      image: "/images/water-bottle.jpg",
      category: "Home & Kitchen",
      rating: 4.7,
      stock: 75,
      brand: "EcoBottle",
      tags: ["water bottle", "stainless steel", "eco-friendly"],
      isNew: true,
      isFeatured: false,
    },
    {
      id: 8,
      name: "4K UHD Smart TV 55 inches",
      description: "Experience the future of entertainment with this 55-inch 4K UHD Smart TV with voice control.",
      price: 599.99,
      discount: 30,
      image: "https://images.samsung.com/is/image/samsung/p6pim/bd/ua55bu8000rsfs/gallery/bd-crystaluhd-bu8000-ua55bu8000rsfs-533633628?$684_547_PNG$",
      category: "Electronics",
      rating: 4.9,
      stock: 20,
      brand: "VisionX",
      tags: ["TV", "smart", "4K"],
      isNew: false,
      isFeatured: true,
    },
    {
      id: 9,
      name: "Yoga Mat with Non-Slip Surface",
      description: "Durable, high-quality yoga mat with a non-slip surface for maximum comfort during your practice.",
      price: 24.99,
      discount: 0,
      image: "/images/yoga-mat.jpg",
      category: "Sports & Outdoors",
      rating: 4.5,
      stock: 120,
      brand: "FitGear",
      tags: ["yoga", "fitness", "sports"],
      isNew: false,
      isFeatured: false,
    },
    {
      id: 10,
      name: "Portable Bluetooth Speaker",
      description: "Compact and waterproof Bluetooth speaker with excellent sound quality and up to 10 hours of playtime.",
      price: 69.99,
      discount: 12,
      image: "/images/bluetooth-speaker.jpg",
      category: "Electronics",
      rating: 4.6,
      stock: 30,
      brand: "SoundWave",
      tags: ["speaker", "bluetooth", "portable"],
      isNew: true,
      isFeatured: false,
    }
  ];
  
  